#!/usr/bin/env python3
"""position_guard.py — 持倉守門工具（2026-09-02 全機制稽核 P3）

把「寫在規則裡、靠人記」的機制接成每日可跑的檢查：
  R14 新倉 30 天閘（持有天數）    R23 認列桶自峰回撤線（arm / 線 / 警報同步）
  R8  梯級停利 GTC 缺口          R19 換手 pair 到期
  >10% 單倉硬線 / 檔數上限         財報 ±48h 窗（R9/R18）
  桶別缺口（roster.json 沒登記的持倉）  旗標一致性（旗標/警報/thesis 三方）

資料源：Firstrade live 持倉（trade_ledger.fetch_positions，失敗退回交易帳 FIFO）、
research/trade-ledger.jsonl、research/roster.json、research/order-registry.json、
research/position-flags.json、research/price-alerts.json、research/thesis-ledger.json、
briefing-out/cache/earnings-dates.json、yfinance 收盤價。

用法：
  python3 tools/position_guard.py                 # 檢查 + 印表 + 寫 research/position-state.json
  python3 tools/position_guard.py --sync-alerts   # 同步 R23 警報（armed 掛、出場撤）
  python3 tools/position_guard.py --render-plan   # 把 roster 表寫進 plan.md 標記區
  python3 tools/position_guard.py --json          # 只印 JSON（給 skill 讀）
退出碼：0 無缺口；2 有缺口（briefing 用來決定是否進 Key Alerts）。
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))

ROSTER = ROOT / "research" / "roster.json"
LEDGER = ROOT / "research" / "trade-ledger.jsonl"
REGISTRY = ROOT / "research" / "order-registry.json"
FLAGS = ROOT / "research" / "position-flags.json"
ALERTS = ROOT / "research" / "price-alerts.json"
THESES = ROOT / "research" / "thesis-ledger.json"
EARN = ROOT / "briefing-out" / "cache" / "earnings-dates.json"
STATE_OUT = ROOT / "research" / "position-state.json"
PLAN = ROOT / "plan.md"
PLAN_BEGIN = "<!-- POSITION-STATE:BEGIN (generated by tools/position_guard.py — do not edit by hand) -->"
PLAN_END = "<!-- POSITION-STATE:END -->"

R23_ARM = 0.20
R23_LINES = (20, 30)
R8_TIERS = ((30, 15), (60, 15), (100, 20))  # (+% 未實現, 該級賣出 % of 原始股數)
R14_DAYS = 30
EARN_WINDOW_DAYS = 2


def _load_json(p, default):
    try:
        return json.loads(Path(p).read_text())
    except Exception:  # noqa: BLE001
        return default


def load_fills():
    out = []
    for line in LEDGER.read_text().splitlines():
        if not line.strip():
            continue
        f = json.loads(line)
        if f.get("is_option"):
            continue
        out.append(f)
    out.sort(key=lambda x: (x["date"], x.get("exec_time", "")))
    return out


def live_positions():
    """Firstrade live；失敗 → None（呼叫端退回 FIFO）。"""
    try:
        import trade_ledger  # noqa: WPS433
        pos = trade_ledger.fetch_positions()
        return pos
    except Exception as e:  # noqa: BLE001
        print(f"[warn] live positions unavailable ({str(e)[:80]}); falling back to ledger FIFO", file=sys.stderr)
        return None


def fifo_positions(fills):
    """從交易帳重建 {SYM: {qty, unit_cost}}（加權平均成本；清倉歸零重算）。"""
    qty, cost = defaultdict(float), defaultdict(float)
    for f in fills:
        s, q, p = f["symbol"], float(f["qty"]), float(f["price"])
        if f["side"] == "BOUGHT":
            qty[s] += q
            cost[s] += q * p
        else:
            if qty[s] > 0:
                avg = cost[s] / qty[s]
                cost[s] -= min(q, qty[s]) * avg
            qty[s] = max(0.0, qty[s] - q)
            if qty[s] < 1e-6:
                qty[s], cost[s] = 0.0, 0.0
    return {s: {"qty": qty[s], "unit_cost": (cost[s] / qty[s]) if qty[s] else 0.0, "last": None,
                "market_value": None} for s in qty if qty[s] > 1e-6}


def open_since(fills, sym):
    """最後一次由 0 建倉的日期（split 不處理；足夠判 R14 與峰值起點）。"""
    sh, since = 0.0, None
    for f in fills:
        if f["symbol"] != sym:
            continue
        if f["side"] == "BOUGHT":
            if sh <= 1e-6:
                since = f["date"]
            sh += float(f["qty"])
        else:
            sh = max(0.0, sh - float(f["qty"]))
    return since


def price_stats(sym, since):
    """(peak_close_since, last_close, peak_date)"""
    import yfinance as yf
    try:
        h = yf.Ticker(sym).history(start=since or "2026-01-01")["Close"].dropna()
        if h.empty:
            return None, None, None
        return float(h.max()), float(h.iloc[-1]), str(h.idxmax().date())
    except Exception as e:  # noqa: BLE001
        print(f"[warn] price history failed {sym}: {e}", file=sys.stderr)
        return None, None, None


def bucket_of(roster, sym):
    for b, syms in roster.get("buckets", {}).items():
        if sym in syms:
            return b
    # R25（2026-09-04）：被動 sleeve ETF（GLD/XLE）視為 sleeve 桶，但不計 18 檔
    if sym in roster.get("passive_sleeve", []):
        return "sleeve(ETF)"
    return None


def open_sell_orders(registry, sym):
    orders = registry.get("orders", registry)
    out = []
    for oid, o in orders.items():
        if o.get("symbol") == sym and o.get("transaction") == "S" and str(o.get("state", "")).startswith(("ORDER-SUBMITTED", "ORDER-REQUESTED")):
            out.append({"id": oid, "shares": o.get("shares"), "limit": o.get("limit_price")})
    return out


def open_flags(flags, sym):
    return [f for f in flags.get("flags", []) if f.get("ticker") == sym and f.get("status") == "open"]


def last_r23_trim_date(flags, sym):
    d = None
    for f in flags.get("flags", []):
        if f.get("ticker") != sym or "r23" not in (f.get("slug") or f.get("id", "")).lower():
            continue
        # trade_ledger.resolve-flag 把結果寫在 history[]（event=resolved, action=trimmed, date），
        # 不是頂層 resolution/resolved_at（2026-09-03 修：AMD 減碼後峰值未重置）
        for h in f.get("history", []):
            if h.get("event") == "resolved" and h.get("action") == "trimmed":
                d = max(d or "", (h.get("date") or "")[:10])
        if f.get("resolution") == "trimmed":
            d = max(d or "", (f.get("resolved_at") or "")[:10])
    return d or None


def alerts_for(alerts, sym):
    return [a for a in alerts.get("alerts", []) if a.get("symbol") == sym and not a.get("status")]


def pending_theses(theses, sym):
    return [t for t in theses.get("theses", []) if t.get("ticker") == sym and t.get("status") == "pending"]


def build_state(*, sync_alerts=False):
    today = dt.date.today()
    roster = _load_json(ROSTER, {})
    fills = load_fills()
    registry = _load_json(REGISTRY, {})
    flags = _load_json(FLAGS, {"flags": []})
    alerts = _load_json(ALERTS, {"alerts": []})
    theses = _load_json(THESES, {"theses": []})
    earn = _load_json(EARN, {}).get("tickers", {})

    live = live_positions()
    if live:
        eq = live["equities"]
        total = float(live.get("total_account_value") or 0) or None
        cash = float(live.get("cash") or 0)
        source = "firstrade-live"
    else:
        eq = fifo_positions(fills)
        total, cash, source = None, None, "ledger-fifo"

    dust = set(roster.get("dust_ignore", []))
    # R24（2026-09-04）：現金停泊工具（SGOV/BIL）視同現金——不佔名額、不進桶別/R23/旗標檢查
    cash_eq = set(roster.get("cash_equivalents", []))
    max_pos = roster.get("max_positions", 18)
    cap_pct = roster.get("single_position_cap_pct", 10.0)

    rows, gaps = [], []
    parked = sum(((v.get("last") or 0) * v["qty"]) for s, v in eq.items() if s in cash_eq and v["qty"] > 0)
    held = [s for s, v in eq.items() if v["qty"] > 0 and s not in dust and s not in cash_eq]
    if total is None and live is None:
        total = None

    for sym in sorted(held):
        v = eq[sym]
        bucket = bucket_of(roster, sym)
        since = open_since(fills, sym)
        days = (today - dt.date.fromisoformat(since)).days if since else None
        peak, last, peak_dt = price_stats(sym, since)
        cost = float(v["unit_cost"] or 0)
        last = last or v.get("last")
        mv = (last or 0) * v["qty"]
        weight = (mv / total * 100) if total else None
        unreal = ((last / cost - 1) * 100) if (last and cost) else None
        dd = ((last / peak - 1) * 100) if (last and peak) else None
        r23_since = since
        trim_dt = last_r23_trim_date(flags, sym)
        if trim_dt:
            r23_since = trim_dt
            peak_t, _, _ = price_stats(sym, trim_dt)
            if peak_t:
                peak, dd = peak_t, ((last / peak_t - 1) * 100 if last else None)
        armed = bool(bucket == "認列" and peak and cost and peak >= cost * (1 + R23_ARM))
        r23_state = None
        if armed and dd is not None:
            r23_state = "TRIGGER −30% 兩段" if dd <= -30 else ("TRIGGER −20% 一段" if dd <= -20 else f"監控中（−20% 線 ${peak*0.8:.0f}）")
        sells = open_sell_orders(registry, sym)
        fl = open_flags(flags, sym)
        al = alerts_for(alerts, sym)
        th = pending_theses(theses, sym)
        e = earn.get(sym, {})
        earn_days = e.get("days_until")
        in_earn_window = earn_days is not None and -EARN_WINDOW_DAYS <= earn_days <= EARN_WINDOW_DAYS
        pair_due = [t["id"] for t in th if "pair" in t["id"].lower()]

        # ── gaps ──
        if bucket is None:
            gaps.append(f"{sym}: 無桶別（roster.json 未登記）→ R8/R23 無法判定")
        elif not roster.get("bucket_confirmed", {}).get(sym, True):
            gaps.append(f"{sym}: 桶別待用戶確認（{bucket}）")
        if weight is not None and weight > cap_pct:
            gaps.append(f"{sym}: 單倉 {weight:.1f}% > {cap_pct:g}% 硬線 → 強制減至 ≤{cap_pct:g}%")
        if bucket == "認列" and unreal is not None:
            for tier_pct, _sell in R8_TIERS:
                if unreal >= tier_pct and not sells:
                    gaps.append(f"{sym}: R8 未實現 +{unreal:.0f}% ≥ +{tier_pct}% 級距但無在掛賣單 → 掛 GTC")
                    break
        if armed:
            # 已破的線交給旗標，不要求警報存在（sync 會主動移除）
            want = {f"{sym}-R23-peakdd{p}" for p in R23_LINES if dd is None or dd > -p}
            have = {a["id"] for a in al if a.get("type") == "peak_dd"}
            missing = want - have
            if missing and not sync_alerts:
                gaps.append(f"{sym}: R23 armed 但缺警報 {sorted(missing)}（--sync-alerts 可補）")
            if r23_state and r23_state.startswith("TRIGGER") and not fl and not sells:
                gaps.append(f"{sym}: R23 {r23_state} 但無旗標 → 收盤確認後 flag + 隔日執行" + ("（財報窗內延後）" if in_earn_window else ""))
        if days is not None and days < R14_DAYS:
            pass  # 資訊列，不是缺口
        for f in fl:
            if f.get("deadline") and f["deadline"] < today.isoformat():
                gaps.append(f"{sym}: 旗標 {f['id']} 已逾期 {f['deadline']}")

        rows.append({
            "symbol": sym, "bucket": bucket, "qty": v["qty"], "unit_cost": round(cost, 2),
            "last": round(last, 2) if last else None, "weight_pct": round(weight, 2) if weight is not None else None,
            "unrealized_pct": round(unreal, 1) if unreal is not None else None,
            "open_since": since, "days_held": days, "r14_locked": bool(days is not None and days < R14_DAYS),
            "peak_close": round(peak, 2) if peak else None, "peak_date": peak_dt,
            "drawdown_from_peak_pct": round(dd, 1) if dd is not None else None,
            "r23_armed": armed, "r23_since": r23_since if armed else None, "r23_state": r23_state,
            "open_sell_orders": sells, "open_flags": [f["id"] for f in fl],
            "alerts": [a["id"] for a in al], "pending_theses": [t["id"] for t in th], "pair_due": pair_due,
            "next_earnings": e.get("next_date"), "earnings_days": earn_days, "in_earnings_window": in_earn_window,
        })

    passive = set(roster.get("passive_sleeve", []))
    n = len([r for r in rows if r["symbol"] not in passive])  # R25：被動 sleeve ETF 不計檔數
    if n > max_pos:
        gaps.append(f"檔數 {n} > 上限 {max_pos} → 砍一進一（R14 鎖定中：{[r['symbol'] for r in rows if r['r14_locked']]}）")
    # roster 內已不在倉的名字 → 提醒清理
    stale = [s for b in roster.get("buckets", {}).values() for s in b if s not in held]
    if stale:
        gaps.append(f"roster.json 含已出場標的 {stale} → 移除")

    state = {"asof": today.isoformat(), "source": source, "total_account_value": total, "cash": cash,
             "parked_cash_equiv": parked, "cash_equivalents": sorted(cash_eq),
             "n_positions": n, "max_positions": max_pos, "positions": rows, "gaps": gaps}

    if sync_alerts:
        changed = _sync_r23_alerts(alerts, rows, today)
        if changed:
            state["alerts_synced"] = changed
    return state


def _sync_r23_alerts(alerts, rows, today):
    """armed → 確保 20/30 兩支 peak_dd 警報存在（since = r23_since）；未 armed/出場 → 移除 R23 警報。"""
    from price_alerts import save_alerts  # noqa: WPS433
    changed = []
    held = {r["symbol"] for r in rows}
    keep = []
    for a in alerts.get("alerts", []):
        if a.get("type") == "peak_dd" and a.get("id", "").split("-R23-")[0] not in held:
            changed.append(f"removed {a['id']}（已出場）")
            continue
        keep.append(a)
    alerts["alerts"] = keep
    have = {a["id"]: a for a in alerts["alerts"]}
    for r in rows:
        sym = r["symbol"]
        if not r["r23_armed"]:
            for p in R23_LINES:
                aid = f"{sym}-R23-peakdd{p}"
                if aid in have:
                    alerts["alerts"] = [a for a in alerts["alerts"] if a["id"] != aid]
                    changed.append(f"removed {aid}（未 armed）")
            continue
        dd = r.get("drawdown_from_peak_pct")
        for p in R23_LINES:
            aid = f"{sym}-R23-peakdd{p}"
            # 已破線 → 交給旗標處理，警報移除（否則 once_per_day 每天重複發）
            if dd is not None and dd <= -p:
                if aid in have:
                    alerts["alerts"] = [a for a in alerts["alerts"] if a["id"] != aid]
                    changed.append(f"removed {aid}（已破線，走旗標）")
                continue
            note = (f"→ 動作：盤中觸價先不動（R17）。收盤確認 ≤ 自峰 −{p}% → 隔日開盤掛賣 1/3 限價貼盤；"
                    f"財報 ±48h 不執行（R9）；觸發即 trade_ledger flag。R23 認列桶自峰回撤線（position_guard 自動維護）")
            if aid in have:
                if have[aid].get("since") != r["r23_since"]:
                    have[aid]["since"] = r["r23_since"]
                    changed.append(f"updated {aid} since→{r['r23_since']}")
                continue
            alerts["alerts"].append({
                "id": aid, "symbol": sym, "type": "peak_dd", "level": float(p), "since": r["r23_since"],
                "note": note, "mode": "once_per_day", "created": today.isoformat(),
                "status": None, "last_fired": None, "fired_count": 0,
            })
            changed.append(f"added {aid}")
    if changed:
        save_alerts(alerts)
    return changed


def render_table(state):
    lines = [
        f"> 生成：{state['asof']}（來源 {state['source']}）｜{state['n_positions']} 檔 / 上限 {state['max_positions']}"
        + (f"｜總值 ${state['total_account_value']:,.0f}｜現金 ${state['cash']:,.0f}" if state.get("total_account_value") else "")
        + (f"（+停泊 SGOV ${state['parked_cash_equiv']:,.0f}，R24 視同現金）" if state.get("parked_cash_equiv") else ""),
        "",
        "| 標的 | 桶 | 股數 | 成本 | 現價 | 權重 | 未實現 | 持有天 | 自峰 | R23 | 在掛賣單 | 旗標 | 財報 |",
        "|---|---|---:|---:|---:|---:|---:|---:|---:|---|---|---|---|",
    ]
    for r in state["positions"]:
        w = f"{r['weight_pct']:.1f}%" if r["weight_pct"] is not None else "—"
        u = f"{r['unrealized_pct']:+.1f}%" if r["unrealized_pct"] is not None else "—"
        d = f"{r['drawdown_from_peak_pct']:+.1f}%" if r["drawdown_from_peak_pct"] is not None else "—"
        days = f"{r['days_held']}{'🔒' if r['r14_locked'] else ''}" if r["days_held"] is not None else "—"
        r23 = (r["r23_state"] or ("armed" if r["r23_armed"] else "—")) if r["bucket"] == "認列" else "豁免"
        sells = ", ".join(f"{o['shares']:g}@{o['limit']:g}" for o in r["open_sell_orders"]) or "—"
        fl = ", ".join(r["open_flags"]) or "—"
        earn = f"{r['next_earnings']}{' ⚠️' if r['in_earnings_window'] else ''}" if r["next_earnings"] else "—"
        lines.append(f"| {r['symbol']} | {r['bucket'] or '❓'} | {r['qty']:g} | {r['unit_cost']:.2f} | {r['last'] or '—'} | {w} | {u} | {days} | {d} | {r23} | {sells} | {fl} | {earn} |")
    if state["gaps"]:
        lines += ["", "**⚠️ 缺口：**"] + [f"- {g}" for g in state["gaps"]]
    else:
        lines += ["", "✅ 無缺口"]
    return "\n".join(lines)


def render_plan(table_md):
    text = PLAN.read_text()
    block = f"{PLAN_BEGIN}\n{table_md}\n{PLAN_END}"
    if PLAN_BEGIN in text and PLAN_END in text:
        pre = text[: text.index(PLAN_BEGIN)]
        post = text[text.index(PLAN_END) + len(PLAN_END):]
        PLAN.write_text(pre + block + post)
    else:
        PLAN.write_text(text.rstrip() + "\n\n## 持倉狀態（自動生成）\n\n" + block + "\n")
    return True


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--sync-alerts", action="store_true")
    ap.add_argument("--render-plan", action="store_true")
    ap.add_argument("--json", action="store_true")
    args = ap.parse_args()

    state = build_state(sync_alerts=args.sync_alerts)
    STATE_OUT.write_text(json.dumps(state, ensure_ascii=False, indent=1))
    table = render_table(state)
    if args.render_plan:
        render_plan(table)
    if args.json:
        print(json.dumps(state, ensure_ascii=False))
    else:
        print(table)
        if state.get("alerts_synced"):
            print("\n🔔 R23 警報同步：" + "; ".join(state["alerts_synced"]))
    return 2 if state["gaps"] else 0


if __name__ == "__main__":
    sys.exit(main())
