#!/usr/bin/env python3
"""position_guard.py — 持倉守門工具（2026-09-02 全機制稽核 P3）

把「寫在規則裡、靠人記」的機制接成每日可跑的檢查：
  R14 新倉 30 天閘（持有天數）    R23 認列桶自峰回撤線（arm / 線 / 警報同步）
  R8  梯級停利 GTC 缺口          R19 換手 pair 到期
  >10% 單倉硬線 / 檔數上限         財報 ±48h 窗（R9/R18）
  C2  R8+R23 合計 30% runner 保底  C3 R14 窗內 R23 不 arm（2026-09-14）
  R16 樂透桶停損單缺口            R24 閒置現金 > $10k
  R28 a) R23 觸線區/減碼後 30 天禁加碼  b) 減碼後跌破成本 → 旗標  c) 單名累計虧損 ≥1.5% 帳戶 → forced 旗標
  R29 a) 認列桶殘倉 <1.5% 不配名額  b) gate ≤ min(財報, 15 交易日)  c) 最弱兩檔（換手對象）
  R30 加碼候選（買強：未實現>0 + revision up>down + 價>SMA50 + 權重<6%）
  R25 修訂 sleeve 帶 4–8% / ETF 自峰 −10% 減至 2% / 帳戶自 sleeve 建立後峰 −10% 賣半 / R8 梯級
  桶別缺口（roster.json 沒登記的持倉）  旗標一致性（旗標/警報/thesis 三方）

資料源：Firstrade live 持倉（trade_ledger.fetch_positions，失敗退回交易帳 FIFO）、
research/trade-ledger.jsonl、research/roster.json、research/order-registry.json、
research/position-flags.json、research/price-alerts.json、research/thesis-ledger.json、
briefing-out/cache/earnings-dates.json、yfinance 收盤價。

用法：
  python3 tools/position_guard.py                 # 檢查 + 印表 + 寫 research/position-state.json
  python3 tools/position_guard.py --sync-alerts   # 同步 R23 警報（armed 掛、出場撤）
  python3 tools/position_guard.py --render-plan   # 把 roster 表寫進 plan.md 標記區
  python3 tools/position_guard.py --json          # 只印 JSON（給 skill 讀）
退出碼：0 無缺口；2 有缺口（briefing 用來決定是否進 Key Alerts）。
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))

ROSTER = ROOT / "research" / "roster.json"
LEDGER = ROOT / "research" / "trade-ledger.jsonl"
REGISTRY = ROOT / "research" / "order-registry.json"
FLAGS = ROOT / "research" / "position-flags.json"
ALERTS = ROOT / "research" / "price-alerts.json"
THESES = ROOT / "research" / "thesis-ledger.json"
EARN = ROOT / "briefing-out" / "cache" / "earnings-dates.json"
STATE_OUT = ROOT / "research" / "position-state.json"
PLAN = ROOT / "plan.md"
PLAN_BEGIN = "<!-- POSITION-STATE:BEGIN (generated by tools/position_guard.py — do not edit by hand) -->"
PLAN_END = "<!-- POSITION-STATE:END -->"

R23_ARM = 0.20
R23_LINES = (20, 30)
R8_TIERS = ((30, 15), (60, 15), (100, 20))  # (+% 未實現, 該級賣出 % of 原始股數)
R14_DAYS = 30
EARN_WINDOW_DAYS = 2
RUNNER_FLOOR_PCT = 30       # C2（2026-09-14）：R8+R23 合計最多賣 70%，30% runner 對兩者合計生效
IDLE_TRIGGER, IDLE_BUFFER_PCT, IDLE_RESERVE_USD = 10_000, 0.03, 8_000   # R24 閒置現金；緩衝 = max(3%, $8k)（2026-09-16 留手動掛單額）
STOP_PRICE_TYPES = {"3", "4"}  # Firstrade price_type：3=stop、4=stop-limit（R16 樂透停損單）
# R28（2026-09-14，CRDO 案）：a) R23 armed 且自峰 ≤ −15% 或 R23 減碼後 30 天內 → 禁向下加碼
#                             b) R23 減碼過且已跌破成本 → 不享 runner 保底，須開旗標（deadline ≤ 15 交易日）
#                             c) 認列桶單名累計虧損（已實現+未實現，自建倉）≥ 1.5% 帳戶 → forced 旗標
R28_BUYLOCK_DD, R28_BUYLOCK_DAYS = -15.0, 30
R28_FLAG_MAX_CAL_DAYS = 21          # ≈ 15 個交易日
R28_LOSS_BUDGET_PCT = 1.5
# R29（2026-09-14，用戶：波段桶機動性要高）：a) 認列桶殘倉 <1.5% 不配名額 → 10 交易日內補到 ≥2% 或清
#   b) 認列桶 thesis gate 最長到 min(下次財報, 15 交易日)  c) 每日排最弱兩檔（90d RS vs SPY + 30d revision），換手只准換這兩檔
R29_TAIL_PCT, R29_TAIL_CAL_DAYS, R29_REBUILD_PCT = 1.5, 14, 2.0
# R30（2026-09-14，CRM 案：只有賣強沒有買強）：加碼候選 = 未實現 >0、30d revision up>down、價 > SMA50、權重 <6%、非 R28a 鎖、非財報窗
R30_MAX_WEIGHT, R30_MAX_USD = 6.0, 3_000
# R25 修訂（2026-09-14）：sleeve 目標 6%、帶 4–8%；ETF 自峰 −10% → 減至 4%；帳戶自 sleeve 建立後峰值 −10% → 賣一半換子彈；GLD/XLE 套 R8 梯級
SLEEVE_TARGET, SLEEVE_LO, SLEEVE_HI, SLEEVE_ETF_DD, SLEEVE_ACCT_DD = 6.0, 4.0, 8.0, -10.0, -10.0
FUND = ROOT / "briefing-out" / "cache" / "fundamentals-snapshot.json"
# H11（2026-09-17）：板塊相對 RS——軟體對 IGV、半導體/硬體對 SMH、其餘對 SPY；R29c 排序仍用 SPY，這欄只顯示與影子計分
SECTOR_ETF = {"IGV": {"CRM", "CRWD", "PLTR", "TWLO", "DDOG", "SNPS", "NOW", "TEAM", "WDAY", "ZS", "NET", "SNOW", "MDB", "INTU", "ADBE", "PANW", "HUBS", "SHOP", "MSFT", "ORCL"},
              "SMH": {"MU", "NVDA", "AVGO", "AMD", "LRCX", "CRDO", "LITE", "ANET", "CLS", "DIOD", "ONTO", "COHR", "MRVL", "TSM", "KLAC", "AMAT", "ASML", "ARM", "SNDK"}}
MARKS = ROOT / "research" / "equity-marks.json"


def _load_json(p, default):
    try:
        return json.loads(Path(p).read_text())
    except Exception:  # noqa: BLE001
        return default


def load_fills():
    out = []
    for line in LEDGER.read_text().splitlines():
        if not line.strip():
            continue
        f = json.loads(line)
        if f.get("is_option"):
            continue
        out.append(f)
    out.sort(key=lambda x: (x["date"], x.get("exec_time", "")))
    return out


def live_positions():
    """Firstrade live；失敗 → None（呼叫端退回 FIFO）。"""
    try:
        import trade_ledger  # noqa: WPS433
        pos = trade_ledger.fetch_positions()
        return pos
    except Exception as e:  # noqa: BLE001
        print(f"[warn] live positions unavailable ({str(e)[:80]}); falling back to ledger FIFO", file=sys.stderr)
        return None


def fifo_positions(fills):
    """從交易帳重建 {SYM: {qty, unit_cost}}（加權平均成本；清倉歸零重算）。"""
    qty, cost = defaultdict(float), defaultdict(float)
    for f in fills:
        s, q, p = f["symbol"], float(f["qty"]), float(f["price"])
        if f["side"] == "BOUGHT":
            qty[s] += q
            cost[s] += q * p
        else:
            if qty[s] > 0:
                avg = cost[s] / qty[s]
                cost[s] -= min(q, qty[s]) * avg
            qty[s] = max(0.0, qty[s] - q)
            if qty[s] < 1e-6:
                qty[s], cost[s] = 0.0, 0.0
    return {s: {"qty": qty[s], "unit_cost": (cost[s] / qty[s]) if qty[s] else 0.0, "last": None,
                "market_value": None} for s in qty if qty[s] > 1e-6}


def open_since(fills, sym):
    """最後一次由 0 建倉的日期（split 不處理；足夠判 R14 與峰值起點）。"""
    sh, since = 0.0, None
    for f in fills:
        if f["symbol"] != sym:
            continue
        if f["side"] == "BOUGHT":
            if sh <= 1e-6:
                since = f["date"]
            sh += float(f["qty"])
        else:
            sh = max(0.0, sh - float(f["qty"]))
    return since


def qty_stats_since(fills, sym, since):
    """建倉起算的最高持股數（R8+R23 合計已賣 % 的分母）。"""
    sh, peak = 0.0, 0.0
    for f in fills:
        if f["symbol"] != sym or (since and f["date"] < since):
            continue
        sh = sh + float(f["qty"]) if f["side"] == "BOUGHT" else max(0.0, sh - float(f["qty"]))
        peak = max(peak, sh)
    return peak


def realized_since(fills, sym, since):
    """建倉起算的已實現損益 + 帳本口徑殘餘股數/平均成本（加權平均成本法）。
    R28c 單名虧損預算：已實現與未實現**同一口徑**（都用交易帳平均成本）；Firstrade 的 unit_cost 是
    另一套 lot 法，混用會讓同一檔算出不同數（CRDO 9/14：−$4.6k vs −$2.0k）。回 (realized, ledger_qty, ledger_avg)。"""
    sh, cost, real = 0.0, 0.0, 0.0
    for f in fills:
        if f["symbol"] != sym or (since and f["date"] < since):
            continue
        q, p = float(f["qty"]), float(f["price"])
        if f["side"] == "BOUGHT":
            sh += q; cost += q * p
        elif sh > 0:
            avg = cost / sh
            q = min(q, sh)
            real += q * (p - avg); cost -= q * avg; sh -= q
    return real, sh, (cost / sh if sh > 1e-6 else None)


def last_r23_trim_price(fills, sym, trim_dt):
    """R23 減碼日（±1 日）該標的最後一筆賣出價；找不到 → None。"""
    if not trim_dt:
        return None
    d0 = dt.date.fromisoformat(trim_dt)
    px = None
    for f in fills:
        if f["symbol"] == sym and f["side"] != "BOUGHT":
            try:
                if abs((dt.date.fromisoformat(f["date"]) - d0).days) <= 1:
                    px = float(f["price"])
            except ValueError:
                continue
    return px


def buys_after(fills, sym, since_date):
    return [f for f in fills if f["symbol"] == sym and f["side"] == "BOUGHT" and since_date and f["date"] > since_date]


def open_buy_orders(registry, sym):
    orders = registry.get("orders", registry)
    return [oid for oid, o in orders.items()
            if o.get("symbol") == sym and o.get("transaction") == "B" and o.get("sec_type") == 1
            and str(o.get("state", "")).startswith(("ORDER-SUBMITTED", "ORDER-REQUESTED"))]


def open_stop_orders(registry, sym):
    orders = registry.get("orders", registry)
    return [oid for oid, o in orders.items()
            if o.get("symbol") == sym and o.get("transaction") == "S" and str(o.get("price_type")) in STOP_PRICE_TYPES
            and str(o.get("state", "")).startswith(("ORDER-SUBMITTED", "ORDER-REQUESTED"))]


def pending_buy_notional(registry):
    orders = registry.get("orders", registry)
    return sum((o.get("shares") or 0) * (o.get("limit_price") or 0) for o in orders.values()
               if o.get("transaction") == "B" and o.get("sec_type") == 1
               and str(o.get("state", "")).startswith(("ORDER-SUBMITTED", "ORDER-REQUESTED")))


def rev_30d(fund, sym):
    """(up, down) 30 日 revision 筆數；curr_q 優先，缺則 curr_fy。抓不到 → (None, None)。"""
    fe = ((fund.get(sym) or {}).get("snapshot") or {}).get("forward_estimates") or {}
    for k in ("curr_q", "curr_fy", "next_fy"):
        b = fe.get(k) or {}
        if b.get("revisions_up_30d") is not None or b.get("revisions_down_30d") is not None:
            return float(b.get("revisions_up_30d") or 0), float(b.get("revisions_down_30d") or 0)
    return None, None


def market_frame(symbols):
    """一次抓 7 個月日線 → {sym: {last, sma20, sma50, high20, ret90}}；SPY 一併抓作 RS 基準。失敗回 {}。"""
    try:
        import yfinance as yf
        syms = sorted(set(symbols) | {"SPY", "IGV", "SMH"})
        px = yf.download(syms, period="14mo", auto_adjust=True, progress=False)["Close"]  # 14 個月供 EMA200 收斂
        out = {}
        for s in syms:
            if s not in px:
                continue
            c = px[s].dropna()
            if len(c) < 60:
                continue
            out[s] = {"last": float(c.iloc[-1]), "sma20": float(c.tail(20).mean()), "sma50": float(c.tail(50).mean()),
                      "ema200": float(c.ewm(span=200, adjust=False).mean().iloc[-1]) if len(c) >= 120 else None,
                      # EMA50 5 日斜率（%）：兩線上子集內 ≥2% → 20 日 4.78%/61.5% vs 3.73%/59.7%；進排序不進閘門（ma-filter-evidence D）
                      "ema50_slope5_pct": float((lambda e: (e.iloc[-1] / e.iloc[-6] - 1) * 100)(c.ewm(span=50, adjust=False).mean())) if len(c) >= 60 else None,
                      # 布林帶寬擠壓：20 日帶寬在近 120 日最低 20%（ma-filter-evidence E：擠壓且兩線上 20 日 4.73%/63.3% vs 3.58%/57.6%）
                      "bb_squeeze": bool((lambda bw: bw.iloc[-1] <= bw.tail(120).quantile(0.2))((c.rolling(20).std() * 4 / c.rolling(20).mean()).dropna())) if len(c) >= 140 else False,
                      "high20": float(c.tail(20).max()), "high60": float(c.tail(60).max()), "high10": float(c.tail(10).max()),
                      "ret90": float(c.iloc[-1] / c.iloc[-min(63, len(c))] - 1)}
        return out
    except Exception as e:  # noqa: BLE001
        print(f"[warn] market_frame failed: {e}", file=sys.stderr)
        return {}


def account_peak_since(since):
    """淨值標記自 since 起的峰值（R25 修訂：sleeve 建立後的回撤才算它的職責）。"""
    m = _load_json(MARKS, {})
    marks = m.get("marks") if isinstance(m, dict) else m
    vals = [x["value"] for x in (marks or []) if not x.get("excluded") and x.get("date", "") >= (since or "")]
    return max(vals) if vals else None


def price_stats(sym, since):
    """(peak_close_since, last_close, peak_date)"""
    import yfinance as yf
    try:
        h = yf.Ticker(sym).history(start=since or "2026-01-01")["Close"].dropna()
        if h.empty:
            return None, None, None
        return float(h.max()), float(h.iloc[-1]), str(h.idxmax().date())
    except Exception as e:  # noqa: BLE001
        print(f"[warn] price history failed {sym}: {e}", file=sys.stderr)
        return None, None, None


def bucket_of(roster, sym):
    for b, syms in roster.get("buckets", {}).items():
        if sym in syms:
            return b
    # R25（2026-09-04）：被動 sleeve ETF（GLD/XLE）視為 sleeve 桶，但不計 18 檔
    if sym in roster.get("passive_sleeve", []):
        return "sleeve(ETF)"
    return None


def open_sell_orders(registry, sym):
    orders = registry.get("orders", registry)
    out = []
    for oid, o in orders.items():
        if o.get("symbol") == sym and o.get("transaction") == "S" and str(o.get("state", "")).startswith(("ORDER-SUBMITTED", "ORDER-REQUESTED")):
            out.append({"id": oid, "shares": o.get("shares"), "limit": o.get("limit_price")})
    return out


def open_flags(flags, sym):
    return [f for f in flags.get("flags", []) if f.get("ticker") == sym and f.get("status") == "open"]


def last_r23_trim_date(flags, sym, fills=None, since=None):
    """峰值起算日 = max(旗標 trimmed 日, 建倉後最近一筆賣出成交日)。
    用成交而不只用旗標（2026-09-15）：pre-close pass 的 day 單成交後 evening pass 要看到峰值已重置，否則同一天賣兩段。"""
    d = None
    for f in (fills or []):
        # VOID（2026-09-22 HWM 案）：被 `trade_ledger.py annotate --evidence "VOID …"` 標記的成交是系統誤觸、已補回，
        # 不得當作減碼 → 不重置峰值、不觸發 R28a 30 天買方鎖
        if str(f.get("origin_evidence") or "").startswith("VOID"):
            continue
        if f["symbol"] == sym and f["side"] != "BOUGHT" and (not since or f["date"] >= since):
            d = max(d or "", f["date"][:10])
    for f in flags.get("flags", []):
        # 任何旗標下的 trimmed（R23 線、用戶收盤線、R28）都重置峰值起算日——MYRG 9/15 走 price-trigger-derating 旗標減 1/3，
        # 若只認 slug 含 r23 的旗標，峰值不重置、隔晚會再賣一段（2026-09-15 修）
        if f.get("ticker") != sym:
            continue
        # 誤觸撤銷（2026-09-22 HWM 案）：旗標最終以「誤觸 / VOID」理由 withdrawn → 其 trimmed 記錄是系統錯誤，
        # 不重置峰值、不觸發 R28a 買方鎖（成交本身另由 trade-ledger VOID 標記排除）
        hist = f.get("history", [])
        if any(h.get("action") == "withdrawn" and any(k in str(h.get("note") or "") for k in ("誤觸", "VOID")) for h in hist):
            continue
        # trade_ledger.resolve-flag 把結果寫在 history[]（event=resolved, action=trimmed, date），
        # 不是頂層 resolution/resolved_at（2026-09-03 修：AMD 減碼後峰值未重置）
        for h in hist:
            # resolved/trimmed（結案）或 trimmed_stage（多段線的中途段，MYRG 9/15）都算一次減碼 → 峰值重算
            if h.get("action") == "trimmed":
                d = max(d or "", (h.get("date") or "")[:10])
        if f.get("resolution") == "trimmed":
            d = max(d or "", (f.get("resolved_at") or "")[:10])
    return d or None


def alerts_for(alerts, sym):
    return [a for a in alerts.get("alerts", []) if a.get("symbol") == sym and not a.get("status")]


def pending_theses(theses, sym):
    return [t for t in theses.get("theses", []) if t.get("ticker") == sym and t.get("status") == "pending"]


def build_state(*, sync_alerts=False):
    today = dt.date.today()
    roster = _load_json(ROSTER, {})
    fills = load_fills()
    registry = _load_json(REGISTRY, {})
    flags = _load_json(FLAGS, {"flags": []})
    alerts = _load_json(ALERTS, {"alerts": []})
    theses = _load_json(THESES, {"theses": []})
    earn = _load_json(EARN, {}).get("tickers", {})

    live = live_positions()
    if live:
        eq = live["equities"]
        total = float(live.get("total_account_value") or 0) or None
        cash = float(live.get("cash") or 0)
        source = "firstrade-live"
    else:
        eq = fifo_positions(fills)
        total, cash, source = None, None, "ledger-fifo"

    dust = set(roster.get("dust_ignore", []))
    # R24（2026-09-04）：現金停泊工具（SGOV/BIL）視同現金——不佔名額、不進桶別/R23/旗標檢查
    cash_eq = set(roster.get("cash_equivalents", []))
    max_pos = roster.get("max_positions", 18)
    cap_pct = roster.get("single_position_cap_pct", 10.0)

    rows, gaps = [], []
    parked = sum(((v.get("last") or 0) * v["qty"]) for s, v in eq.items() if s in cash_eq and v["qty"] > 0)
    held = [s for s, v in eq.items() if v["qty"] > 0 and s not in dust and s not in cash_eq]
    fund = _load_json(FUND, {})
    fund = fund.get("tickers", fund)
    bench_cfg = _load_json(ROOT / "research" / "bench.json", {})
    bench = [s for s in (bench_cfg.get("L1", []) + bench_cfg.get("L2", [])) if s not in held]
    mkt = market_frame(held + bench)
    spy_ret90 = (mkt.get("SPY") or {}).get("ret90")
    add_candidates, sleeve_actions, washout_candidates = [], [], []
    if total is None and live is None:
        total = None

    for sym in sorted(held):
        v = eq[sym]
        bucket = bucket_of(roster, sym)
        since = open_since(fills, sym)
        # 帳本尚無建倉成交（當日新買、ledger 未入帳）→ 視為今日建倉，fail-closed：R14 鎖、R23 不 arm、峰值不從 1/1 起算
        # （2026-09-22 HWM 案：9/21 12:00 起手 13 股，15:45 pre-close pass 時 since=None → R14 未鎖 + 峰值取 1/1 起 → 誤觸 R23-20 賣 4 股）
        if since is None:
            since = today.isoformat()
        days = (today - dt.date.fromisoformat(since)).days if since else None
        peak, last, peak_dt = price_stats(sym, since)
        cost = float(v["unit_cost"] or 0)
        last = last or v.get("last")
        mv = (last or 0) * v["qty"]
        weight = (mv / total * 100) if total else None
        unreal = ((last / cost - 1) * 100) if (last and cost) else None
        dd = ((last / peak - 1) * 100) if (last and peak) else None
        r23_since = since
        # 兩個日期：peak 起算用「任何賣出」（R8 級距賣在高點，之後峰值重算合理）；
        # R28a 買方鎖 / R28b 輸家判定只用「防守型減碼」（旗標 trimmed = R23 / 用戶收盤線），R8 harvest 不鎖買（CRM 9/2 案）
        trim_dt = last_r23_trim_date(flags, sym, fills, since)
        def_trim_dt = last_r23_trim_date(flags, sym)
        if trim_dt:
            r23_since = trim_dt
            peak_t, _, _ = price_stats(sym, trim_dt)
            if peak_t:
                peak, dd = peak_t, ((last / peak_t - 1) * 100 if last else None)
        r14_locked = bool(days is not None and days < R14_DAYS)
        # C3（2026-09-14 裁決）：R14 30 天窗內 R23 不 arm（新倉不掛回撤線；auto_exec 同步跳過）
        armed = bool(bucket == "認列" and not r14_locked and peak and cost and peak >= cost * (1 + R23_ARM))
        r23_state = None
        if armed and dd is not None:
            r23_state = "TRIGGER −30% 兩段" if dd <= -30 else ("TRIGGER −20% 一段" if dd <= -20 else f"監控中（−20% 線 ${peak*0.8:.0f}）")
        elif bucket == "認列" and r14_locked and peak and cost and peak >= cost * (1 + R23_ARM):
            r23_state = "R14 鎖（未 arm）"
        sells = open_sell_orders(registry, sym)
        # C2：R8 + R23 合計已賣 %（分母 = 建倉起最高持股），30% runner 保底對兩者合計生效
        peak_qty = qty_stats_since(fills, sym, since) or v["qty"]
        cum_sold = max(0.0, (peak_qty - v["qty"]) / peak_qty * 100) if peak_qty else 0.0
        pending_sell = sum(float(o.get("shares") or 0) for o in sells)
        sellable_left = max(0.0, peak_qty * (1 - RUNNER_FLOOR_PCT / 100) - (peak_qty - v["qty"]))
        runner_floor_hit = bool(bucket == "認列" and cum_sold >= 100 - RUNNER_FLOOR_PCT - 1e-6)
        fl = open_flags(flags, sym)
        al = alerts_for(alerts, sym)
        th = pending_theses(theses, sym)
        e = earn.get(sym, {})
        earn_days = e.get("days_until")
        in_earn_window = earn_days is not None and -EARN_WINDOW_DAYS <= earn_days <= EARN_WINDOW_DAYS
        pair_due = [t["id"] for t in th if "pair" in t["id"].lower()]

        # ── gaps ──
        if bucket is None:
            gaps.append(f"{sym}: 無桶別（roster.json 未登記）→ R8/R23 無法判定")
        elif not roster.get("bucket_confirmed", {}).get(sym, True):
            gaps.append(f"{sym}: 桶別待用戶確認（{bucket}）")
        if weight is not None and weight > cap_pct:
            gaps.append(f"{sym}: 單倉 {weight:.1f}% > {cap_pct:g}% 硬線 → 強制減至 ≤{cap_pct:g}%")
        if bucket == "認列" and runner_floor_hit:
            if sells:
                gaps.append(f"{sym}: R8+R23 合計已賣 {cum_sold:.0f}% ≥ 70%，觸 30% runner 保底 → 撤在掛減碼單 {[o['id'] for o in sells]}（C2）")
        elif bucket == "認列" and pending_sell > sellable_left + 1e-6:
            gaps.append(f"{sym}: 在掛賣單 {pending_sell:g} 股 > 保底前可賣 {sellable_left:.0f} 股（已賣 {cum_sold:.0f}%）→ 縮單，勿賣穿 30% runner（C2）")
        if bucket == "認列" and unreal is not None and not runner_floor_hit:
            for tier_pct, _sell in R8_TIERS:
                if unreal >= tier_pct and not sells:
                    gaps.append(f"{sym}: R8 未實現 +{unreal:.0f}% ≥ +{tier_pct}% 級距但無在掛賣單 → 掛 GTC")
                    break
        if bucket == "樂透" and not open_stop_orders(registry, sym):
            gaps.append(f"{sym}: 樂透桶無在掛停損單 → 掛普通停損（R16；成本線，非移動）")

        # ── R28（CRDO 案）──
        up, down = rev_30d(fund, sym)
        buy_lock = None
        trim_recent = bool(def_trim_dt and (today - dt.date.fromisoformat(def_trim_dt)).days <= R28_BUYLOCK_DAYS)
        if bucket == "認列" and armed and dd is not None and dd <= R28_BUYLOCK_DD:
            buy_lock = f"R23 armed 且自峰 {dd:+.0f}% ≤ −15%"
        elif bucket == "認列" and trim_recent:
            # R28a 提前解鎖（2026-09-15，AMD 案）：價已收回 R23 減碼價之上且 30d revision up>down = whipsaw 已確認，
            # 繼續鎖只會重演「只低接不追強」；解鎖後交 R30 判定（仍需價 > SMA50）
            trim_px = last_r23_trim_price(fills, sym, def_trim_dt)
            if trim_px and last and last > trim_px and up is not None and up > down:
                buy_lock = None
            else:
                buy_lock = f"R23 減碼 {def_trim_dt} 後 30 天內" + (f"（收回 {trim_px:.0f} 且 rev up>down 即解鎖）" if trim_px else "")
        if buy_lock:
            bo = open_buy_orders(registry, sym)
            if bo:
                gaps.append(f"{sym}: R28a 禁向下加碼（{buy_lock}）但有在掛買單 {bo} → 撤單")
            recent = buys_after(fills, sym, def_trim_dt) if trim_recent else []
            if recent:
                gaps.append(f"{sym}: R28a 違規——R23 減碼後又買 {sum(float(b['qty']) for b in recent):g} 股（{[b['date'] for b in recent]}）→ journal 標 ⚠️ R28 bypass")
        realized, ledger_qty, ledger_avg = realized_since(fills, sym, since)
        # 口徑統一：帳本股數對得上 live 股數（±1）才用帳本平均成本算未實現；對不上（早期 lot 不在帳本）退回 Firstrade 成本並標記
        if ledger_avg and abs(ledger_qty - v["qty"]) <= 1.0:
            unreal_usd, basis = ((last - ledger_avg) * v["qty"] if last else 0.0), "ledger"
        else:
            unreal_usd, basis = (((last - cost) * v["qty"]) if (last and cost) else 0.0), "firstrade(帳本股數不符)"
        cum_pnl = realized + unreal_usd
        loss_budget_hit = bool(bucket == "認列" and total and cum_pnl <= -R28_LOSS_BUDGET_PCT / 100 * total)
        loser_after_trim = bool(bucket == "認列" and def_trim_dt and unreal is not None and unreal <= -5.0)  # −5% 容差，避免 DDOG −0% 型噪音
        if loser_after_trim or loss_budget_hit:
            why = []
            if loser_after_trim:
                why.append(f"R28b R23 已減碼且跌破成本 {unreal:+.0f}%，殘倉不享 runner 保底")
            if loss_budget_hit:
                why.append(f"R28c 累計虧損 ${cum_pnl:,.0f}（已實現 {realized:,.0f} + 未實現 {unreal_usd:,.0f}）≥ {R28_LOSS_BUDGET_PCT}% 帳戶")
            if not fl:
                gaps.append(f"{sym}: {'；'.join(why)} → 開 forced 旗標（deadline ≤ 15 交易日）：清倉或明文 withdrawn")
            else:
                for f in fl:
                    dl = f.get("deadline")
                    if dl and (dt.date.fromisoformat(dl) - today).days > R28_FLAG_MAX_CAL_DAYS and not any(a.get("type") == "price_below" for a in al):
                        gaps.append(f"{sym}: 旗標 {f['id']} deadline {dl} 超過 15 交易日且無價格線（{why[0][:20]}…）→ 縮 deadline 或掛收盤線")
        if armed:
            # 已破的線交給旗標，不要求警報存在（sync 會主動移除）
            want = {f"{sym}-R23-peakdd{p}" for p in R23_LINES if dd is None or dd > -p}
            have = {a["id"] for a in al if a.get("type") == "peak_dd"}
            missing = want - have
            if missing and not sync_alerts:
                gaps.append(f"{sym}: R23 armed 但缺警報 {sorted(missing)}（--sync-alerts 可補）")
            if r23_state and r23_state.startswith("TRIGGER") and not fl and not sells:
                gaps.append(f"{sym}: R23 {r23_state} 但無旗標 → 收盤確認後 flag + 隔日執行" + ("（財報窗內延後）" if in_earn_window else ""))
        if days is not None and days < R14_DAYS:
            pass  # 資訊列，不是缺口
        for f in fl:
            if f.get("deadline") and f["deadline"] < today.isoformat():
                gaps.append(f"{sym}: 旗標 {f['id']} 已逾期 {f['deadline']}")

        # ── R29 / R30 / R25 修訂 ──
        mf = mkt.get(sym) or {}
        rs90 = (mf["ret90"] - spy_ret90) * 100 if (mf.get("ret90") is not None and spy_ret90 is not None) else None
        sec_etf = next((etf for etf, members in SECTOR_ETF.items() if sym in members), "SPY")
        sec_ret = (mkt.get(sec_etf) or {}).get("ret90")
        rs90_sec = (mf["ret90"] - sec_ret) * 100 if (mf.get("ret90") is not None and sec_ret is not None) else None
        if bucket == "認列" and weight is not None and weight < R29_TAIL_PCT:
            ok_flag = [f for f in fl if f.get("deadline") and (dt.date.fromisoformat(f["deadline"]) - today).days <= R29_TAIL_CAL_DAYS]
            if not ok_flag:
                gaps.append(f"{sym}: R29a 認列桶殘倉 {weight:.1f}% < {R29_TAIL_PCT}% 不配名額 → 10 個交易日內補到 ≥{R29_REBUILD_PCT:g}%（thesis 確認且未 R28a 鎖）或清倉；開旗標 deadline ≤ {(today + dt.timedelta(days=R29_TAIL_CAL_DAYS)).isoformat()}")
        if bucket == "認列":
            cap_dl = today + dt.timedelta(days=R28_FLAG_MAX_CAL_DAYS)
            if e.get("next_date"):
                try:
                    cap_dl = min(cap_dl, dt.date.fromisoformat(e["next_date"]))
                except ValueError:
                    pass
            for f in fl:
                dl = f.get("deadline")
                if dl and dt.date.fromisoformat(dl) > cap_dl and not any(a.get("type") == "price_below" for a in al):
                    gaps.append(f"{sym}: R29b 認列桶 gate deadline {dl} 超過 min(下次財報, 15 交易日)={cap_dl}，且無價格線 → 縮 deadline 或掛收盤線")
        # 未實現 ≥ +3%（不是 >0）：LITE 9/16 +0.2% 也算「贏家」是噪音；買強要買的是已經證明自己的部位
        # EMA200 第二濾網（2026-09-17，30 檔×5 年回測）：>SMA50 且 >EMA200 20 日均 +3.73%/勝率 59.7%；
        # >SMA50 但 <EMA200 的那 8.4% 時間只有 +1.59%/50.4% —— 這層濾掉的就是那塊。EMA50 不如 SMA50，不採。
        above_e200 = bool(mf.get("ema200") and last and last > mf["ema200"]) if mf.get("ema200") else True  # 資料不足不擋
        add_ok = (bucket in ("認列", "信念") and unreal is not None and unreal >= 3.0 and up is not None and up > down
                  and mf.get("sma50") and last and last > mf["sma50"] and above_e200
                  and weight is not None and weight < R30_MAX_WEIGHT
                  and not buy_lock and not in_earn_window)
        if add_ok:
            room = min(R30_MAX_USD, (R30_MAX_WEIGHT - weight) / 100 * total) if total else R30_MAX_USD
            add_candidates.append({"symbol": sym, "bucket": bucket, "weight_pct": round(weight, 2), "unrealized_pct": round(unreal, 1),
                                   "ema50_slope5_pct": round(mf["ema50_slope5_pct"], 2) if mf.get("ema50_slope5_pct") is not None else None,
                                   "strength": ("強" if (mf.get("ema50_slope5_pct") or 0) >= 2.0 else "普"),
                                   "bb_squeeze": bool(mf.get("bb_squeeze")),
                                   "rev_up_30d": up, "rev_down_30d": down, "last": round(last, 2), "sma20": round(mf["sma20"], 2),
                                   "sma50": round(mf["sma50"], 2), "high20": round(mf["high20"], 2), "room_usd": round(room, 0),
                                   "structure": "回檔 SMA20 限價 GTC（10 日）或收盤突破 20 日高隔日接；單次 ≤$3k"})
        # 影子：深洗盤買點（2026-09-16 用戶「買在高點殺在低點卻沒逢低抄底」）——自 60 日高 ≤ −30% 且 30d revision up>down
        # 且收盤站回 10 日高（止穩），記 cf-washout-buy（correct_if over）；20 天內同標的不重複。只記錄不下單：
        # 7/25 檢討「下跌中深檔買梯」−$5.7k vs ICHR 型錯砍 −32%，兩個方向都有代價，先累樣本再談規則。
        if bucket in ("認列", "信念") and mf.get("high60") and last and up is not None:
            dd60 = last / mf["high60"] - 1
            if dd60 <= -0.30 and up > down and last >= mf.get("high10", 0) and not in_earn_window:
                washout_candidates.append({"symbol": sym, "dd60_pct": round(dd60 * 100, 1), "rev": f"{up:g}↑:{down:g}↓", "last": round(last, 2)})
        if bucket == "sleeve(ETF)":
            if unreal is not None and unreal >= R8_TIERS[0][0] and not sells:
                gaps.append(f"{sym}: R25 修訂 sleeve 未實現 +{unreal:.0f}% ≥ +30% 無在掛賣單 → 套 R8 梯級收割進 SGOV")
            if dd is not None and dd <= SLEEVE_ETF_DD and weight is not None and weight > SLEEVE_LO / 2:
                sleeve_actions.append({"symbol": sym, "action": "TRIM", "why": f"自峰 {dd:+.0f}% ≤ −10%", "target_weight_pct": SLEEVE_LO / 2})
                gaps.append(f"{sym}: R25 修訂 sleeve ETF 自峰 {dd:+.0f}% → 減至 {SLEEVE_LO/2:g}%（賣出去 SGOV）")

        rows.append({
            "symbol": sym, "bucket": bucket, "qty": v["qty"], "unit_cost": round(cost, 2),
            "rs90_vs_spy_pct": round(rs90, 1) if rs90 is not None else None, "rev_up_30d": up, "rev_down_30d": down,
            "sector_etf": sec_etf, "rs90_vs_sector_pct": round(rs90_sec, 1) if rs90_sec is not None else None,
            "ema200": round(mf["ema200"], 2) if mf.get("ema200") else None, "above_ema200": above_e200,
            "above_sma50": bool(mf.get("sma50") and last and last > mf["sma50"]),
            "last": round(last, 2) if last else None, "weight_pct": round(weight, 2) if weight is not None else None,
            "unrealized_pct": round(unreal, 1) if unreal is not None else None,
            "open_since": since, "days_held": days, "r14_locked": r14_locked,
            "peak_qty": peak_qty, "cum_sold_pct": round(cum_sold, 1), "sellable_before_floor": int(sellable_left),
            "runner_floor_hit": runner_floor_hit,
            "buy_locked": buy_lock, "realized_since_open": round(realized, 2), "cum_pnl_usd": round(cum_pnl, 2),
            "ledger_unit_cost": round(ledger_avg, 2) if ledger_avg else None, "pnl_basis": basis,
            "loss_budget_hit": loss_budget_hit, "loser_after_trim": loser_after_trim,
            "peak_close": round(peak, 2) if peak else None, "peak_date": peak_dt,
            "drawdown_from_peak_pct": round(dd, 1) if dd is not None else None,
            "r23_armed": armed, "r23_since": r23_since if armed else None, "r23_state": r23_state,
            "open_sell_orders": sells, "open_flags": [f["id"] for f in fl],
            "alerts": [a["id"] for a in al], "pending_theses": [t["id"] for t in th], "pair_due": pair_due,
            "next_earnings": e.get("next_date"), "earnings_days": earn_days, "in_earnings_window": in_earn_window,
        })

    # R30 候選排序：擠壓中的優先（63% 勝率），其次 EMA50 斜率；機器一次只掛一梯時先掛排前面的
    add_candidates.sort(key=lambda c: (not c.get("bb_squeeze"), -(c.get("ema50_slope5_pct") or -99)))

    passive = set(roster.get("passive_sleeve", []))
    n = len([r for r in rows if r["symbol"] not in passive])  # R25：被動 sleeve ETF 不計檔數
    # R29c：認列桶最弱兩檔（90d RS vs SPY 由弱到強，同 RS 看 revision 淨值）——換手只准換這兩檔
    harvest_rows = [r for r in rows if r["bucket"] == "認列" and r.get("rs90_vs_spy_pct") is not None]
    ranked = sorted(harvest_rows, key=lambda r: (r["rs90_vs_spy_pct"], (r.get("rev_up_30d") or 0) - (r.get("rev_down_30d") or 0)))
    weakest_two = [{"symbol": r["symbol"], "rs90_vs_spy_pct": r["rs90_vs_spy_pct"], "rev": f"{r.get('rev_up_30d') or 0:g}↑:{r.get('rev_down_30d') or 0:g}↓",
                    "weight_pct": r["weight_pct"], "unrealized_pct": r["unrealized_pct"],
                    "rs90_vs_sector": f"{r.get('rs90_vs_sector_pct'):+.1f}pp vs {r.get('sector_etf')}" if r.get("rs90_vs_sector_pct") is not None else None} for r in ranked[:2]]
    if n > max_pos:
        gaps.append(f"檔數 {n} > 上限 {max_pos} → 砍一進一，換手對象限 R29c 最弱兩檔 {[w['symbol'] for w in weakest_two]}（R14 鎖定中：{[r['symbol'] for r in rows if r['r14_locked']]}）")
    # ── R29d 節奏輪動（2026-09-17）：候補綜合分連續 ≥10 個交易日高於最弱在倉 ≥ 門檻，且距上次換手 ≥14 天 → 換一檔 ──
    #   綜合分 = 板塊相對 RS90(pp) + 30 × 30 日淨修正比 − max(priced_in,0)/10。出場 60 天內的名字門檻加倍（治 STRL/LITE 來回）。
    def _score(sym, mf_, up_, down_, n_, pin_):
        if not mf_ or mf_.get("ret90") is None:
            return None
        etf = next((e for e, m in SECTOR_ETF.items() if sym in m), "SPY")
        base = (mkt.get(etf) or {}).get("ret90")
        if base is None:
            return None
        rs = (mf_["ret90"] - base) * 100
        net = ((up_ or 0) - (down_ or 0)) / max(n_ or 1, 1) if up_ is not None else 0.0
        pin = max(pin_ or 0, 0)
        # EMA50 5 日斜率項：clip 到 [−2, 4]% × 5 → −10 ~ +20 分（2026-09-17 加；斜率 Q5 較 Q3 多約 +2pp 20 日報酬）
        slope = max(-2.0, min(4.0, mf_.get("ema50_slope5_pct") or 0.0))
        return round(rs + 30 * net - pin / 10 + 5 * slope, 1)

    def _rev_n(sym):
        fe = ((fund.get(sym) or {}).get("snapshot") or {}).get("forward_estimates") or {}
        for k in ("curr_fy", "curr_q", "next_fy"):
            b = fe.get(k) or {}
            if b.get("revisions_up_30d") is not None or b.get("revisions_down_30d") is not None:
                return float(b.get("revisions_up_30d") or 0), float(b.get("revisions_down_30d") or 0), b.get("eps_num_analysts")
        return None, None, None

    def _pin(sym):
        return ((fund.get(sym) or {}).get("self_valuation") or {}).get("priced_in_pct")

    R29D_GAP, R29D_STREAK, R29D_MIN_DAYS = 15.0, 10, 14
    rot_path = ROOT / "research" / "rotation-state.json"
    rot = _load_json(rot_path, {"streak": 0, "last_swap": None, "history": []})
    exits_60d = {}
    for f in fills:
        if f["side"] != "BOUGHT" and (today - dt.date.fromisoformat(f["date"])).days <= 60:
            exits_60d[f["symbol"]] = f["date"]
    held_scores = []
    for r in rows:
        if r["bucket"] != "認列" or r["r14_locked"] or r.get("in_earnings_window"):
            continue
        s = _score(r["symbol"], mkt.get(r["symbol"]), r.get("rev_up_30d"), r.get("rev_down_30d"), None, _pin(r["symbol"]))
        if s is not None:
            held_scores.append((s, r["symbol"]))
    bench_scores = []
    for b in bench:
        up_, down_, n_ = _rev_n(b)
        s = _score(b, mkt.get(b), up_, down_, n_, _pin(b))
        if s is None:
            continue
        mb = mkt.get(b) or {}
        # R29d 換入門檻：候補須在 SMA50 與 EMA200 之上（與 R30 同濾網），在線下的名字不進換手比較
        if not (mb.get("sma50") and mb.get("last") and mb["last"] > mb["sma50"] and (not mb.get("ema200") or mb["last"] > mb["ema200"])):
            continue
        hurdle = R29D_GAP * (2 if b in exits_60d else 1)
        bench_scores.append((s, b, hurdle, up_, down_))
    rotation = {"asof": today.isoformat(), "weakest": None, "top_bench": None, "gap": None, "streak": rot.get("streak", 0), "last_swap": rot.get("last_swap"), "due": False}
    if held_scores and bench_scores:
        w_s, w_sym = min(held_scores)
        b_s, b_sym, hurdle, b_up, b_dn = max(bench_scores)
        gap = round(b_s - w_s, 1)
        # 只在新交易日推進 streak
        if rot.get("last_check") != today.isoformat():
            rot["streak"] = rot.get("streak", 0) + 1 if gap >= hurdle else 0
            rot["last_check"] = today.isoformat()
        days_since = (today - dt.date.fromisoformat(rot["last_swap"])).days if rot.get("last_swap") else 999
        due = rot["streak"] >= R29D_STREAK and days_since >= R29D_MIN_DAYS and gap >= hurdle
        rotation.update({"weakest": {"symbol": w_sym, "score": w_s}, "top_bench": {"symbol": b_sym, "score": b_s, "hurdle": hurdle, "rev": f"{b_up or 0:g}↑:{b_dn or 0:g}↓"},
                         "gap": gap, "streak": rot["streak"], "due": due,
                         "bench_ranked": [{"symbol": x[1], "score": x[0]} for x in sorted(bench_scores, reverse=True)[:6]],
                         "held_ranked": [{"symbol": x[1], "score": x[0]} for x in sorted(held_scores)[:4]]})
        if due:
            gaps.append(f"R29d 輪動到期：{b_sym}（分 {b_s}，rev {b_up or 0:g}↑:{b_dn or 0:g}↓）連 {rot['streak']} 日勝最弱在倉 {w_sym}（分 {w_s}）≥{hurdle:g} → 換手：賣 {w_sym}、{b_sym} starter ≤2%；不換要寫理由（forced 旗標 5 日）")
    # 偵測換手已發生：bench 名字出現在持倉 → 記 last_swap、streak 歸零
    if any(s in held for s in (bench_cfg.get("L1", []) + bench_cfg.get("L2", []))) and rot.get("last_swap") != today.isoformat():
        newly = [s for s in (bench_cfg.get("L1", []) + bench_cfg.get("L2", [])) if s in held]
        rot["last_swap"] = today.isoformat(); rot["streak"] = 0
        rot.setdefault("history", []).append({"date": today.isoformat(), "entered": newly})
    rot_path.write_text(json.dumps(rot, ensure_ascii=False, indent=1))

    # R25 修訂：sleeve 帶寬 4–8% + 帳戶自 sleeve 建立後峰值 −10% → 賣一半換子彈
    sleeve_rows = [r for r in rows if r["bucket"] == "sleeve(ETF)"]
    sleeve_w = sum(r["weight_pct"] or 0 for r in sleeve_rows)
    sleeve_since = min([r["open_since"] for r in sleeve_rows if r.get("open_since")], default=None)
    acct_peak = account_peak_since(sleeve_since) if sleeve_since else None
    acct_dd = ((total / acct_peak - 1) * 100) if (acct_peak and total) else None
    # regime 覆寫（tools/fomc_watch.py 寫：Fed 實際升息 → 目標 8%；R25 規則 1）
    ovr = _load_json(ROOT / "research" / "regime-overrides.json", {})
    sleeve_target = float(ovr.get("sleeve_target_pct") or SLEEVE_TARGET)
    sleeve_hi = max(SLEEVE_HI, sleeve_target + 2.0)
    if sleeve_rows and sleeve_target > SLEEVE_TARGET and sleeve_w < sleeve_target - 0.5:
        gaps.append(f"R25 規則 1 sleeve 目標 {sleeve_target:g}%（{ovr.get('reason','regime 覆寫')}）> 現 {sleeve_w:.1f}% → 分兩批補到 {sleeve_target:g}%（auto_exec G）")
        sleeve_actions.append({"symbol": "SLEEVE", "action": "BUY_TO", "target_weight_pct": sleeve_target, "why": ovr.get("reason", "regime 覆寫")})
    if sleeve_rows:
        if sleeve_w > sleeve_hi:
            gaps.append(f"R25 修訂 sleeve 合計 {sleeve_w:.1f}% > {sleeve_hi:g}% 上緣 → 減回 {sleeve_target:g}%（賣出去 SGOV）")
            sleeve_actions.append({"symbol": "SLEEVE", "action": "TRIM_TO", "target_weight_pct": sleeve_target, "why": f"合計 {sleeve_w:.1f}% > {sleeve_hi:g}%"})
        elif sleeve_w < SLEEVE_LO and sleeve_target <= SLEEVE_TARGET:
            gaps.append(f"R25 修訂 sleeve 合計 {sleeve_w:.1f}% < {SLEEVE_LO:g}% 下緣 → 補回 {SLEEVE_TARGET:g}%（除非帳戶回撤觸發賣半中）")
        if acct_dd is not None and acct_dd <= SLEEVE_ACCT_DD:
            gaps.append(f"R25 修訂 帳戶自 sleeve 建立（{sleeve_since}）後峰值 ${acct_peak:,.0f} 回撤 {acct_dd:+.1f}% ≤ −10% → sleeve 賣一半換子彈（進 SGOV，redeploy 走飛輪）")
            sleeve_actions.append({"symbol": "SLEEVE", "action": "SELL_HALF", "why": f"帳戶自 sleeve 建立後峰值回撤 {acct_dd:+.1f}%"})
    # R20 撿回條目雙分支驗證（2026-09-14 程式化）：pending reentry-* 必含回檔與走強兩分支
    for t in theses.get("theses", []):
        if t.get("status") != "pending" or "reentry" not in (t.get("slug") or "") or t.get("ticker") in held:
            continue  # 已撿回/在倉者不是撿回條目（LITE 8/14 案）
        txt = (t.get("thesis") or "") + " ".join(t.get("falsification") or [])
        has_low = any(k in txt for k in ("回檔", "①", "跌回", "接回"))
        has_high = any(k in txt for k in ("走強", "②", "創新高", "追強", "重新提名"))
        if not (has_low and has_high):
            gaps.append(f"{t['id']}: R20 撿回條目單分支（缺{'回檔' if not has_low else '走強'}分支）→ `thesis_ledger.py add` 同 slug 覆寫成雙分支")
    # roster 內已不在倉的名字 → 提醒清理
    stale = [s for b in roster.get("buckets", {}).values() for s in b if s not in held]
    if stale:
        gaps.append(f"roster.json 含已出場標的 {stale} → 移除")

    # R24：閒置現金 = 現金 − 在掛買單 − 3% 緩衝；> $10k → 缺口（auto_exec D 段出 SGOV 單）
    pend_buy = pending_buy_notional(registry)
    idle = (cash - pend_buy - max(IDLE_BUFFER_PCT * total, IDLE_RESERVE_USD)) if (cash is not None and total) else None
    if idle is not None and idle > IDLE_TRIGGER:
        gaps.append(f"R24 閒置現金 ${idle:,.0f}（現金 {cash:,.0f} − 在掛買 {pend_buy:,.0f} − 3% 緩衝）> $10k → 掛 SGOV GTC 買至 ≤ $5k")

    # 影子帳登錄（去重 20 天）
    if washout_candidates:
        import subprocess
        shadow = ROOT / "research" / "shadow-signals.jsonl"
        recent = set()
        if shadow.exists():
            for line in shadow.read_text().splitlines()[-400:]:
                try:
                    r = json.loads(line)
                except Exception:  # noqa: BLE001
                    continue
                if r.get("kind") == "cf-washout-buy" and (today - dt.date.fromisoformat(r.get("date", "2000-01-01")[:10])).days <= 20:
                    recent.add(r.get("ticker"))
        for w in washout_candidates:
            if w["symbol"] in recent:
                continue
            subprocess.run([sys.executable, str(ROOT / "tools" / "shadow_signals.py"), "record", "--kind", "cf-washout-buy",
                            "--ticker", w["symbol"], "--price", str(w["last"]), "--size", "3000", "--correct-if", "over",
                            "--note", f"深洗盤買點影子：自 60 日高 {w['dd60_pct']}%、rev {w['rev']}、站回 10 日高；假設買 $3k starter"],
                           capture_output=True, text=True, timeout=60)

    state = {"asof": today.isoformat(), "source": source, "total_account_value": total, "cash": cash,
             "pending_buy_notional": round(pend_buy, 2), "idle_cash": round(idle, 2) if idle is not None else None,
             "parked_cash_equiv": parked, "cash_equivalents": sorted(cash_eq),
             "n_positions": n, "max_positions": max_pos, "positions": rows, "gaps": gaps,
             "weakest_two": weakest_two, "add_candidates": add_candidates, "washout_candidates": washout_candidates,
             "rotation": rotation,
             "sleeve": {"weight_pct": round(sleeve_w, 2), "since": sleeve_since, "acct_peak_since": acct_peak,
                        "acct_dd_pct": round(acct_dd, 1) if acct_dd is not None else None, "actions": sleeve_actions}}

    if sync_alerts:
        changed = _sync_r23_alerts(alerts, rows, today)
        if changed:
            state["alerts_synced"] = changed
    return state


def _sync_r23_alerts(alerts, rows, today):
    """armed → 確保 20/30 兩支 peak_dd 警報存在（since = r23_since）；未 armed/出場 → 移除 R23 警報。"""
    from price_alerts import save_alerts  # noqa: WPS433
    changed = []
    held = {r["symbol"] for r in rows}
    keep = []
    for a in alerts.get("alerts", []):
        if a.get("type") == "peak_dd" and a.get("id", "").split("-R23-")[0] not in held:
            changed.append(f"removed {a['id']}（已出場）")
            continue
        keep.append(a)
    alerts["alerts"] = keep
    have = {a["id"]: a for a in alerts["alerts"]}
    for r in rows:
        sym = r["symbol"]
        if not r["r23_armed"]:
            for p in R23_LINES:
                aid = f"{sym}-R23-peakdd{p}"
                if aid in have:
                    alerts["alerts"] = [a for a in alerts["alerts"] if a["id"] != aid]
                    changed.append(f"removed {aid}（未 armed）")
            continue
        dd = r.get("drawdown_from_peak_pct")
        for p in R23_LINES:
            aid = f"{sym}-R23-peakdd{p}"
            # 已破線 → 交給旗標處理，警報移除（否則 once_per_day 每天重複發）
            if dd is not None and dd <= -p:
                if aid in have:
                    alerts["alerts"] = [a for a in alerts["alerts"] if a["id"] != aid]
                    changed.append(f"removed {aid}（已破線，走旗標）")
                continue
            note = (f"→ 動作：本線只認收盤（close_confirm，盤中不發）。收盤 ≤ 自峰 −{p}% → auto_exec 晚間 pass 自動掛賣 1/3（gt90，次日生效）；"
                    f"財報 ±48h 不執行（R9）；觸發即 trade_ledger flag。R23 認列桶自峰回撤線（position_guard 自動維護）")
            if aid in have:
                if have[aid].get("mode") != "close_confirm":
                    have[aid]["mode"] = "close_confirm"; changed.append(f"{aid} mode→close_confirm")
                if have[aid].get("since") != r["r23_since"]:
                    have[aid]["since"] = r["r23_since"]
                    changed.append(f"updated {aid} since→{r['r23_since']}")
                continue
            alerts["alerts"].append({
                "id": aid, "symbol": sym, "type": "peak_dd", "level": float(p), "since": r["r23_since"],
                "note": note, "mode": "close_confirm", "created": today.isoformat(),
                "status": None, "last_fired": None, "fired_count": 0,
            })
            changed.append(f"added {aid}")
    if changed:
        save_alerts(alerts)
    return changed


def render_table(state):
    lines = [
        f"> 生成：{state['asof']}（來源 {state['source']}）｜{state['n_positions']} 檔 / 上限 {state['max_positions']}"
        + (f"｜總值 ${state['total_account_value']:,.0f}｜現金 ${state['cash']:,.0f}" if state.get("total_account_value") else "")
        + (f"（+停泊 SGOV ${state['parked_cash_equiv']:,.0f}，R24 視同現金）" if state.get("parked_cash_equiv") else ""),
        "",
        "| 標的 | 桶 | 股數 | 成本 | 現價 | 權重 | 未實現 | 持有天 | 自峰 | R23 | 已賣% | 在掛賣單 | 旗標 | 財報 |",
        "|---|---|---:|---:|---:|---:|---:|---:|---:|---|---:|---|---|---|",
    ]
    for r in state["positions"]:
        w = f"{r['weight_pct']:.1f}%" if r["weight_pct"] is not None else "—"
        u = f"{r['unrealized_pct']:+.1f}%" if r["unrealized_pct"] is not None else "—"
        d = f"{r['drawdown_from_peak_pct']:+.1f}%" if r["drawdown_from_peak_pct"] is not None else "—"
        days = f"{r['days_held']}{'🔒' if r['r14_locked'] else ''}" if r["days_held"] is not None else "—"
        r23 = (r["r23_state"] or ("armed" if r["r23_armed"] else "—")) if r["bucket"] == "認列" else "豁免"
        sells = ", ".join(f"{o['shares']:g}@{o['limit']:g}" for o in r["open_sell_orders"]) or "—"
        fl = ", ".join(r["open_flags"]) or "—"
        earn = f"{r['next_earnings']}{' ⚠️' if r['in_earnings_window'] else ''}" if r["next_earnings"] else "—"
        sold = (f"{r['cum_sold_pct']:.0f}%" + ("🛑" if r.get("runner_floor_hit") else "")) if r["bucket"] == "認列" and r.get("cum_sold_pct") else "—"
        if r.get("buy_locked"):
            sold += "🚫買"
        lines.append(f"| {r['symbol']} | {r['bucket'] or '❓'} | {r['qty']:g} | {r['unit_cost']:.2f} | {r['last'] or '—'} | {w} | {u} | {days} | {d} | {r23} | {sold} | {sells} | {fl} | {earn} |")
    if state.get("weakest_two"):
        lines += ["", "**R29c 認列桶最弱兩檔（換手只准換這兩檔）：** " + "；".join(
            f"{w['symbol']} RS90 {w['rs90_vs_spy_pct']:+.1f}pp vs SPY（{w.get('rs90_vs_sector') or '—'}）、rev {w['rev']}、{w['weight_pct']:.1f}%" for w in state["weakest_two"])]
    rt = state.get("rotation") or {}
    if rt.get("weakest") and rt.get("top_bench"):
        lines += ["", f"**R29d 輪動：** 最弱在倉 {rt['weakest']['symbol']}（{rt['weakest']['score']}）vs 候補最強 {rt['top_bench']['symbol']}（{rt['top_bench']['score']}，rev {rt['top_bench']['rev']}）差 {rt['gap']}（門檻 {rt['top_bench']['hurdle']:g}）｜連續 {rt['streak']}/10 日｜上次換手 {rt.get('last_swap') or '—'}"
                  + ("｜**到期**" if rt.get("due") else "")
                  + "；候補排名 " + "、".join(f"{x['symbol']} {x['score']}" for x in rt.get("bench_ranked", []))]
    if state.get("add_candidates"):
        lines += ["", "**R30 加碼候選（買強）：** " + "；".join(
            f"{c['symbol']}[{c.get('strength','')}斜率{c.get('ema50_slope5_pct') if c.get('ema50_slope5_pct') is not None else '—'}%{'·擠壓' if c.get('bb_squeeze') else ''}] +{c['unrealized_pct']:.0f}% rev {c['rev_up_30d']:g}↑:{c['rev_down_30d']:g}↓ 現 {c['last']} / SMA20 {c['sma20']} / 20日高 {c['high20']}，額度 ${c['room_usd']:,.0f}" for c in state["add_candidates"])]
    else:
        lines += ["", "R30 加碼候選：無（條件＝未實現>0、30d revision up>down、價>SMA50、權重<6%、非 R28a 鎖、非財報窗）"]
    sl = state.get("sleeve") or {}
    if sl.get("since"):
        lines += [f"sleeve {sl['weight_pct']:.1f}%（帶 4–8%）｜帳戶自 {sl['since']} 峰 ${sl['acct_peak_since'] or 0:,.0f} 回撤 {sl['acct_dd_pct']:+.1f}%（−10% 賣半換子彈）"]
    if state["gaps"]:
        lines += ["", "**⚠️ 缺口：**"] + [f"- {g}" for g in state["gaps"]]
    else:
        lines += ["", "✅ 無缺口"]
    return "\n".join(lines)


def render_plan(table_md):
    text = PLAN.read_text()
    block = f"{PLAN_BEGIN}\n{table_md}\n{PLAN_END}"
    if PLAN_BEGIN in text and PLAN_END in text:
        pre = text[: text.index(PLAN_BEGIN)]
        post = text[text.index(PLAN_END) + len(PLAN_END):]
        PLAN.write_text(pre + block + post)
    else:
        PLAN.write_text(text.rstrip() + "\n\n## 持倉狀態（自動生成）\n\n" + block + "\n")
    return True


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--sync-alerts", action="store_true")
    ap.add_argument("--render-plan", action="store_true")
    ap.add_argument("--json", action="store_true")
    args = ap.parse_args()

    state = build_state(sync_alerts=args.sync_alerts)
    STATE_OUT.write_text(json.dumps(state, ensure_ascii=False, indent=1))
    table = render_table(state)
    if args.render_plan:
        render_plan(table)
    if args.json:
        print(json.dumps(state, ensure_ascii=False))
    else:
        print(table)
        if state.get("alerts_synced"):
            print("\n🔔 R23 警報同步：" + "; ".join(state["alerts_synced"]))
    return 2 if state["gaps"] else 0


if __name__ == "__main__":
    sys.exit(main())
